name: Check CODEOWNERS Entries

on:
  push:
    branches:
      - lhattamer-codeowners-entry-gha # temp for testing files

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Check CODEOWNERS exists for new files
      run: |
        chmod +x .github/scripts/check_codeowners.sh
        .github/scripts/check_codeowners.sh

    - name: Check CODEOWNERS for removal when files deleted
      run: |
        chmod +x .github/scripts/check_deleted_files.sh
        .github/scripts/check_deleted_files.sh
